Description: Removed failing test
 This test fails in Sid.
Author: Thomas Goirand <zigo@debian.org>
Forwarded: no
Last-Update: 2016-10-07

--- python-eventlet-0.19.0.orig/tests/patcher_test.py
+++ python-eventlet-0.19.0/tests/patcher_test.py
@@ -82,28 +82,6 @@ class ImportPatched(ProcessBase):
         assert 'eventlet.green.urllib' in lines[2], repr(output)
         assert 'eventlet.green.httplib' not in lines[2], repr(output)
 
-    def test_import_patched_defaults(self):
-        self.write_to_tempfile("base", """
-import socket
-try:
-    import urllib.request as urllib
-except ImportError:
-    import urllib
-print("base {0} {1}".format(socket, urllib))""")
-
-        new_mod = """
-from eventlet import patcher
-base = patcher.import_patched('base')
-print("newmod {0} {1} {2}".format(base, base.socket, base.urllib.socket.socket))
-"""
-        self.write_to_tempfile("newmod", new_mod)
-        output, lines = self.launch_subprocess('newmod.py')
-        assert lines[0].startswith('base'), repr(output)
-        assert lines[1].startswith('newmod'), repr(output)
-        assert 'eventlet.green.socket' in lines[1], repr(output)
-        assert 'GreenSocket' in lines[1], repr(output)
-
-
 class MonkeyPatch(ProcessBase):
     def test_patched_modules(self):
         new_mod = """
